### ISSUE TITLE
Cannot find path while attempting to manually apply HideRecommendedSection 

### ISSUE THREAD

**Issue by beeradmoore** [SimonCropp/WinDebloat#23]
#### Describe the bug

Unable to manually apply `StartMenuRecommendations`.

![Screenshot 2023-08-06 124258](https://github.com/SimonCropp/WinDebloat/assets/904737/e883a518-6865-49f7-8bef-f47754b91c2e)
(EDIT: This does not use the original format from the current readme but the updated format from #22, as far as I know this should not be a problem)

Confirmed the entry does not exist in regedit. 
![Screenshot 2023-08-06 124635](https://github.com/SimonCropp/WinDebloat/assets/904737/95e40651-4c9a-438d-9805-f4e6bedbe554)

#### Minimal Repro

Attempting to execute
```ps
Set-ItemProperty -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Name "HideRecommendedSection" -Type "DWord" -Value "1"
```

#### Additional notes
It appears from multiple sites ([source 1](https://www.thewindowsclub.com/remove-recommended-section-from-start-menu-in-windows), [source 2](https://winaero.com/windows-11-now-has-the-option-to-remove-recommended-from-start-but-you-cant-use-it/)) that if they key does not exist it should be created. 

The docs for [Set-ItemProperty](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-itemproperty?view=powershell-7.3) seem to indicate it will create things, but maybe it only creates keys and not entries? (unsure of correct names, from the above regedit screenshot keys = things on right, entries = things on the left)

**Comment by SimonCropp** [comment]
actually i will just add a note about creating the parent for that item https://github.com/SimonCropp/WinDebloat/commit/e630591dcb8459222160f68ec80c082e6cf72496
