### ISSUE TITLE
More services that can be stopped/disabled

### ISSUE THREAD

**Issue by pamanes** [SimonCropp/WinDebloat#30]
**Connected User Experiences and Telemetry**: it will disable Feedback, Telemetry and Data Collection. https://github.com/SimonCropp/WinDebloat/pull/32
**Downloaded Maps Manager**: if you don’t use the Bing Maps app. https://github.com/SimonCropp/WinDebloat/pull/33
**Infrared monitor service**: if you never use File transfer via infrared devices.
**Internet Connection Sharing**: it is an old service that can be disabled. https://github.com/SimonCropp/WinDebloat/pull/34
**Parental Control**: if you don’t use the Parental Control feature.
**Remote Registry**: you’d better disable it. Then, no one can access your Registry remotely.
**Windows Insider Service**: if you are not a part of the Windows Insider Program.

**Comment by SimonCropp** [comment]
seems Remote Registry is note enabled by default?

**Comment by SimonCropp** [comment]
same for insider service?

**Comment by SimonCropp** [comment]
same for parental controls

**Comment by SimonCropp** [comment]
seems Infrared monitor service is not in win11 by default? https://dataloggerinc.com/news-article/irda-windows-11/
