### ISSUE TITLE
Allow exclusions to be provided

### ISSUE THREAD

**Issue by SeanFeldman** [SimonCropp/WinDebloat#5]
#### Is the feature request related to a problem

Some of the built-in tools are useful ([example](https://twitter.com/davidebbo/status/1686759068604452865)) and it should be possible to exclude those from the uninstall by providing a list.

#### Describe the solution

Allow a switch to exclude certain apps from the uninstall.

**Comment by impworks** [comment]
I agree. For example, I personally use Microsoft Todo and XBox Game Bar (very useful for screen recording) and wouldn't want to uninstall them as well
